### ISSUE TITLE
[Feat] 시작 페이지 / 관리자 페이지 제작

### ISSUE THREAD

**Issue by JeongRon** [42organization/BlindCodeGame#2]
## Desc

- 시작 페이지 제작
- 관리자 페이지 제작

## Detail

- 시작 페이지 UI 제작 및 API 연결
- 관리자 페이지 UI 제작 API 연결

## Todo
- [x] 시작 페이지 UI 제작
- [x] 시작 페이지 API 연결
- [x] 관리자 페이지 UI 제작
- [x] 관리자 페이지 API 연결
